### PR TITLE
Fix max block size check

### LINKED ISSUE #15: decodedLen() assumes max of int64, but format limits block size to uint32
In `decodedLen()`,

```go
	if uint64(int(v)) != v {
		return 0, 0, errors.New("snappy: decoded block is too large")
	}
```

However, the snappy format description (and the C and C++ implementations) limit this varint to 32-bits:

https://github.com/google/snappy/blob/master/format_description.txt

>The stream starts with the uncompressed length (up to a maximum of 2^32 - 1),
> stored as a little-endian varint.

This check should instead use
```go
	if uint64(uint32(v)) != v {
		return 0, 0, errors.New("snappy: decoded block is too large")
	}
```

I can file a PR here or a CL if this project is using gerrit if you'd like.

This bug dates from the Go 1.1 integer size change.

### PR DESCRIPTION
**Pull request by dgryski**
Since Go 1.1, `int` has been 64-bits on 64-bit platforms instead of
32-bits.  This patch fixes the check to make sure the uncompressed
length is at most 2^32-1 bytes.

Fixes #15

### CODE REVIEW

File: decode.go [hunk 1]
```diff
@@ -30,8 +32,8 @@ func decodedLen(src []byte) (blockLen, headerLen int, err error) {
 	if n <= 0 {
 		return 0, 0, ErrCorrupt
 	}
-	if uint64(int(v)) != v {
-		return 0, 0, errors.New("snappy: decoded block is too large")
+	if uint64(uint32(v)) != v {
```
Comment (nigeltao) [inline decode.go]: An easier and more explicit check is

if v >= 0xffffffff {

Still, there's a number of possible checks we could do here.

One is whether the reported v is <= 1<<32-1 as per https://github.com/google/snappy/blob/master/format_description.txt. The code prior to this patch does not check for this, and you do check for this now. This check is a property of the bytes on the wire, not the GOARCH.

Two is whether that value is representable as an int, the same type used to represent the length of a slice. This check is that the code prior to this patch attempts to do, and you no longer check for this: 1<<32-1 is a valid length according to the format, but returning that as an int is not do-able on GOARCH=arm. We should still check for this.

Related to that is whether int(v) can somehow be negative even if the above checks pass. Compare:
http://play.golang.org/p/-rQWyQ0wUU
http://play.golang.org/p/ba_TIO0bax

File: decode.go [hunk 2]
```diff
@@ -15,6 +15,8 @@ var (
 	ErrCorrupt = errors.New("snappy: corrupt input")
 	// ErrUnsupported reports that the input isn't supported.
 	ErrUnsupported = errors.New("snappy: unsupported input")
+	// ErrTooLarge reports the uncompressed length is too large
```
Comment (nigeltao) [inline decode.go]: s/the/that the/

File: snappy_test.go [hunk 3]
```diff
@@ -86,6 +86,16 @@ func TestInvalidVarint(t *testing.T) {
 	if _, err := Decode(nil, data); err != ErrCorrupt {
 		t.Errorf("Decode: got %v, want ErrCorrupt", err)
 	}
+
+	// varint > 32-bits
+	data = []byte("\xff\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00")
```
Comment (nigeltao) [inline snappy_test.go]: I think that you only need one "\x00".

File: decode.go (hunk 1 above)
Comment (dgryski) [inline decode.go]: I'll push the simpler check (against 0xffffffff), although I think it should be `>`, since 2^32-1 is still a valid length.

I agree about the signed/unsigned slice length problems. Maybe we need to say that slices >2G can't be uncompressed on 32-bit platforms via the `Decode()` API?  Using the `Reader()` interface should still be fine though.

Comment (nigeltao) [inline decode.go]: Yes, it should be > not >=.

I don't think it needs explicit documentation. ioutil.ReadFile will fail if it tries to read a 5G file on a 32-bit platform.

Still, it does need to be explicitly checked for, and return different errors for "too large to represent on this computer" and "invalid on any computer".

File: decode.go [hunk 4]
```diff
@@ -15,6 +15,8 @@ var (
 	ErrCorrupt = errors.New("snappy: corrupt input")
 	// ErrUnsupported reports that the input isn't supported.
 	ErrUnsupported = errors.New("snappy: unsupported input")
+	// ErrTooLarge reports that the uncompressed length is too large
```
Comment (nigeltao) [inline decode.go]: Add a full stop.

Comment (dgryski) [inline decode.go]: Done.

**Comment by dgryski** [comment]
Ping.

**Comment by nigeltao** [comment]
Ah, I left a comment on an outdated diff that still needs doing. Perhaps you didn't see that. (I'm still pretty new to the github code review workflow). Here's a copy/paste:

----

Yes, it should be > not >=.

I don't think it needs explicit documentation. ioutil.ReadFile will fail if it tries to read a 5G file on a 32-bit platform.

Still, it [int(v) can somehow be negative even if the above checks pass] does need to be explicitly checked for, and return different errors for "too large to represent on this computer" and "invalid on any computer".

----

**Comment by dgryski** [comment]
Updated.  This patch checks the word size and returns ErrTooLarge if the uncompressed size is > 0x7fffffff on a 32-bit machine.  ErrCorrupt is returned if v > 0xffffffff.  On a 64-bit machine, the ErrTooLarge check is optimized out due to constant folding.

File: decode.go [hunk 5]
```diff
@@ -15,6 +15,8 @@ var (
 	ErrCorrupt = errors.New("snappy: corrupt input")
 	// ErrUnsupported reports that the input isn't supported.
 	ErrUnsupported = errors.New("snappy: unsupported input")
+	// ErrTooLarge reports that the uncompressed length is too large.
+	ErrTooLarge = errors.New("snappy: decoded block is too large")
```
Comment (nigeltao) [inline decode.go]: Please keep these sorted.

File: decode.go [hunk 6]
```diff
@@ -27,12 +29,16 @@ func DecodedLen(src []byte) (int, error) {
...
 func decodedLen(src []byte) (blockLen, headerLen int, err error) {
 	v, n := binary.Uvarint(src)
-	if n <= 0 {
+	if n <= 0 || v > 0xffffffff {
 		return 0, 0, ErrCorrupt
 	}
-	if uint64(int(v)) != v {
-		return 0, 0, errors.New("snappy: decoded block is too large")
+
+	const wordsize = 32 << (^uint(0) >> 32 & 1)
```
Comment (nigeltao) [inline decode.go]: s/wordsize/wordSize/

File: decode.go [hunk 7]
```diff
@@ -27,12 +29,16 @@ func DecodedLen(src []byte) (int, error) {
...
+
```
Comment (nigeltao) [inline decode.go]: Delete the blank line.

File: snappy_test.go [hunk 8]
```diff
@@ -86,6 +86,16 @@ func TestInvalidVarint(t *testing.T) {
 	if _, err := Decode(nil, data); err != ErrCorrupt {
 		t.Errorf("Decode: got %v, want ErrCorrupt", err)
 	}
+
+	// varint > 32-bits
```
Comment (nigeltao) [inline snappy_test.go]: Please make this a complete sentence:
// The encoded varint overflows 32 bits.

**Comment by dgryski** [comment]
Assuming I deleted the correct blank line, these are all done.

**Comment by nigeltao** [comment]
Thanks!
